---
- name: Include variables
  include_vars: "main.yml"

- name: Install EPEL in CentOS
  include_role:
    name: geerlingguy.repo-epel
  when: ansible_distribution == 'CentOS'

- name: Register required variables for yum
  set_fact:
    "{{ ansible_pkg_mgr }}_packages":
      - git
      - python3-pip
  when: ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf"

- name: Register packages for APT
  set_fact:
    "{{ ansible_pkg_mgr }}_packages":
      - git
      - python3-pip
  when: ansible_pkg_mgr == "apt"

- name: Ensure required packages are installed
  include_role:
    name: frite.recon_package_manager

- name: Clone tools  # noqa 401
  git:
    repo: "{{ item.value.url }}"
    dest: "/usr/local/src/{{ item.value.name }}"
    update: true
    force: true
  loop: "{{ py3_clone_tools|dict2items }}"
  when: py3_clone_tools is defined
  changed_when: false

- name: Install setuptools
  pip:
    name: setuptools
    extra_args: --ignore-installed
    executable: pip3
  changed_when: false

- name: Install pip requirements
  pip:
    requirements: "/usr/local/src/{{ item }}/requirements.txt"
    extra_args: --ignore-installed
    executable: pip3
  loop: "{{ py3_pip_args }}"
  when: py3_pip_args is defined

- name: Python3 setup.py installs
  shell: "set -o pipefail; export {{ locale[ansible_distribution] }} && /usr/bin/python3 setup.py install"
  args:
    warn: false
    chdir: "/usr/local/src/{{ item }}/"
    executable: '/bin/bash'
  loop: "{{ py3_setup_files }}"
  when: py3_setup_files is defined
  changed_when: false

- name: Create softlinks
  file:
    src: "/usr/local/src/{{ item.value.repo }}/{{ item.value.file }}"
    dest: "/usr/local/bin/{{ item.value.soft_link }}"
    owner: root
    group: root
    mode: '0755'
    state: link
  loop: "{{ py3_soft_links|dict2items }}"
  when: py3_soft_links is defined
  changed_when: false
